openapi: 3.0.1
info:
  title: Veka.DataDiensten.Api
  description: Platform voor het consulteren van data gekend door VEKA
  version: v1
paths:
  /api/datadiensten/v1/mcs/meldingen:
    get:
      tags:
        - Mcs
      summary: Geeft keuringen en onderhouden terug voor een specifiek gebouwEenheidId
      parameters:
        - name: gebouwEenheidId
          in: query
          description: de id van het gebouw
          required: true
          schema:
            type: integer
            format: int64
        - name: X-Authenticated-UserId
          in: header
          description: Bevat gebruikersinformatie over welke gebruiker deze oproep doet
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Veka.Sophie.DataDiensten.Api.Contract.Mcs.MeldingenLijst'
            application/json:
              schema:
                $ref: '#/components/schemas/Veka.Sophie.DataDiensten.Api.Contract.Mcs.MeldingenLijst'
            text/json:
              schema:
                $ref: '#/components/schemas/Veka.Sophie.DataDiensten.Api.Contract.Mcs.MeldingenLijst'
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Veka.Sophie.Api.Contract.Fout'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Veka.Sophie.Api.Contract.Fout'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Veka.Sophie.Api.Contract.Fout'
        '500':
          description: Server Error
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Veka.Sophie.Api.Contract.Fout'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Veka.Sophie.Api.Contract.Fout'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Veka.Sophie.Api.Contract.Fout'
        '503':
          description: Server Error
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Veka.Sophie.Api.Contract.Fout'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Veka.Sophie.Api.Contract.Fout'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Veka.Sophie.Api.Contract.Fout'
components:
  schemas:
    Veka.Sophie.Api.Contract.Fout:
      type: object
      properties:
        bron:
          enum:
            - None
            - Magda
            - Sophie
          type: string
        dienst:
          type: string
          nullable: true
        diagnose:
          type: string
          nullable: true
        identificatie:
          type: string
          nullable: true
        referte:
          type: string
          nullable: true
      additionalProperties: false
    Veka.Sophie.DataDiensten.Api.Contract.Mcs.Eindbeoordeling:
      type: object
      properties:
        isRookgasafvoerkanaalConform:
          type: boolean
          nullable: true
        isStookplaatsConform:
          type: boolean
          nullable: true
        isStooktoestelConform:
          type: boolean
          nullable: true
        isToestelWerkingGoed:
          type: boolean
        isToestelWerkingVeilig:
          type: boolean
        isVerbrandingscontroleConform:
          type: boolean
          nullable: true
      additionalProperties: false
    Veka.Sophie.DataDiensten.Api.Contract.Mcs.Gegevensactiviteit:
      type: object
      properties:
        type:
          type: string
          nullable: true
        uitvoeringsDatum:
          type: string
          format: date
        wettelijkVerplicht:
          type: boolean
        adresId:
          type: string
          nullable: true
        gebouwEenheidId:
          type: string
          nullable: true
        erkenningsnummer:
          type: string
          nullable: true
      additionalProperties: false
    Veka.Sophie.DataDiensten.Api.Contract.Mcs.KenmerkenToestel:
      type: object
      properties:
        fabricatienummer:
          type: string
          nullable: true
        brandstof:
          type: string
          nullable: true
        merk:
          type: string
          nullable: true
        type:
          type: string
          nullable: true
        bouwjaar:
          type: integer
          format: int32
          nullable: true
      additionalProperties: false
    Veka.Sophie.DataDiensten.Api.Contract.Mcs.Melding:
      type: object
      properties:
        meldingId:
          type: string
          format: uuid
        geldigTot:
          type: string
          format: date
          nullable: true
        eindbeoordeling:
          $ref: '#/components/schemas/Veka.Sophie.DataDiensten.Api.Contract.Mcs.Eindbeoordeling'
        activiteit:
          $ref: '#/components/schemas/Veka.Sophie.DataDiensten.Api.Contract.Mcs.Gegevensactiviteit'
        toestel:
          $ref: '#/components/schemas/Veka.Sophie.DataDiensten.Api.Contract.Mcs.KenmerkenToestel'
        toestelEindbeoordeling:
          enum:
            - Goedgekeurd
            - Afgekeurd
          type: string
      additionalProperties: false
    Veka.Sophie.DataDiensten.Api.Contract.Mcs.MeldingenLijst:
      type: object
      properties:
        meldingen:
          type: array
          items:
            $ref: '#/components/schemas/Veka.Sophie.DataDiensten.Api.Contract.Mcs.Melding'
          nullable: true
      additionalProperties: false
tags:
  - name: Mcs
    description: Service voor informatie over stooktoestellen