openapi: 3.0.1
info:
  title: Veka.Datadiensten.Api
  description: Platform voor het consulteren van data gekend door VEKA
  version: v1
paths:
  /api/datadiensten/v1/gebouweenheden/epc-labels:
    get:
      tags:
        - Gebouweenheden
      summary: 'Geeft de epc labels terug voor de Gebouweenheden van de gegeven locatie, typelocatie, typegebouw en referentiedatum'
      parameters:
        - name: locatie
          in: query
          description: 'De locatie van het gebouw. Default: VLAANDEREN indien locatie ontbreekt'
          schema:
            type: string
        - name: typeLocatie
          in: query
          description: 'Het type locatie (VLAANDEREN, PROVINCIE, GEMEENTE). Default: VLAANDEREN indien typeLocatie ontbreekt.'
          schema:
            type: string
        - name: typeGebouw
          in: query
          description: 'het type van het gebouw (ALLE TYPES, ALLE WONINGEN, GESLOTEN, HALFOPEN, OPEN, APPARTEMENT).'
          schema:
            type: string
        - name: referentieJaar
          in: query
          description: 'Het kadasterjaar van het label. Default: het laatste jaar waarover epc-labels beschikbaar zijn indien referentieJaar ontbreekt.'
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Gebouweenheden.EpcLabelsLijst'
              example: {"labels":[{"locatie":"ANTWERPEN","typeLocatie":"GEMEENTE","typeGebouw":"ALLE WONINGEN","referentiejaar":2024,"totaalAangiftesGeoLocatie":23,"totaalEpcGeoLocatie":68,"geldig":true,"bouwjaren":{"alle":25,"tot2006":12,"na2006":13},"labels":{"APlus":0.5,"A":0.5}},{"locatie":"VLAANDEREN","typeLocatie":"VLAANDEREN","typeGebouw":"APPARTEMENT","referentiejaar":2023,"totaalAangiftesGeoLocatie":27,"totaalEpcGeoLocatie":67,"geldig":false,"bouwjaren":{"alle":25,"tot2006":12,"na2006":13},"labels":null}]}
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example: {"type":"https://datatracker.ietf.org/doc/html/rfc2616#section-10.5.1","title":"Onverwachte fout","status":500,"detail":"Er is een onverwachte fout opgetreden. Raadpleeg de logs voor meer informatie. CorrelatieId = f2b23ca0-9f9e-4d81-86f3-5ea6aa9611f0"}
  /api/datadiensten/v1/mcs/meldingen:
    get:
      tags:
        - Mcs
      summary: Geeft keuringen en onderhouden terug voor een specifiek gebouweenheidId
      parameters:
        - name: gebouweenheidId
          in: query
          description: de id van het gebouw
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mcs.MeldingenLijst'
              example: {"meldingen":[{"meldingId":"0ba8ab6e-d135-4470-a544-7a6550727c03","geldigTot":"2025-01-01","toestelEindbeoordeling":"Goedgekeurd","eindbeoordeling":{"isRookgasafvoerkanaalConform":true,"isStookplaatsConform":null,"isStooktoestelConform":true,"isToestelWerkingGoed":true,"isToestelWerkingVeilig":true,"isVerbrandingscontroleConform":null},"activiteit":{"type":"ONDERHOUD_STOOKTOESTEL","uitvoeringsDatum":"2024-01-01","wettelijkVerplicht":true,"adresId":"4996611","gebouweenheidId":"7299482","erkenningsnummer":"GV49852"},"toestel":{"fabricatienummer":"8290-569-028711-7126010889","brandstof":"AARDGAS","merk":"Junkers","type":"CONDENSERENDE_KETEL","bouwjaar":2012,"vermogen":25}},{"meldingId":"e5247220-3be7-44bf-9ef6-b8389989eb87","geldigTot":null,"toestelEindbeoordeling":"Afgekeurd","eindbeoordeling":{"isRookgasafvoerkanaalConform":false,"isStookplaatsConform":null,"isStooktoestelConform":false,"isToestelWerkingGoed":false,"isToestelWerkingVeilig":false,"isVerbrandingscontroleConform":null},"activiteit":{"type":"KEURING_STOOKTOESTEL","uitvoeringsDatum":"2024-07-08","wettelijkVerplicht":true,"adresId":"2999623","gebouweenheidId":"15995133","erkenningsnummer":"GV56111"},"toestel":{"fabricatienummer":"8290-569-028711-7126010889","brandstof":"HOUTPELLETS","merk":"VAILLANT","type":"ONBEKEND","bouwjaar":2024,"vermogen":25.5}}]}
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example: {"type":"https://datatracker.ietf.org/doc/html/rfc2616#section-10.5.1","title":"Onverwachte fout","status":500,"detail":"Er is een onverwachte fout opgetreden. Raadpleeg de logs voor meer informatie. CorrelatieId = 93135e22-d413-4ba9-9ab8-81146df77817"}
  /api/datadiensten/v1/mvp/werken:
    get:
      tags:
        - Mvp
      summary: Geeft werken terug voor een specifiek gebouweenheidId
      parameters:
        - name: gebouweenheidId
          in: query
          description: de id van de gebouweenheid
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mvp.WerkenLijst'
              example: {"werken":[{"werkId":"87a2c980c7ab1576c310d42765b79c12d02beb00d93970b239692487681d85e3","type":"navullenSpouwmuur","dossierNummer":"23-MVP-000001","facturatieDatum":null,"gebouweenheidId":10057485,"adresId":1384090,"uitvoeringsdatum":"2023-01-03","uitvoerder":"aannemer","netbeheerder":null,"dak":null,"buitenmuur":{"type":null,"teVerwijderenAsbest":false,"oppervlakteAsbest":null,"oppervlakte":null,"dikteSpouw":45.10,"lambdaWaarde":0.035,"rdWaarde":null,"stsNummer":"4568745236"},"vloer":null,"ramenEnDeuren":null,"elektriciteitEnSanitair":null,"hernieuwbareEnergieproductie":null,"gascondensatieketel":null},{"werkId":"821f307234185a4be1e9fd6f5d7e53445c768d3bd25eeeef1ba0981a6b38e747","type":"elektriciteit","dossierNummer":"23-MVP-000006","facturatieDatum":"2022-05-02","gebouweenheidId":10057485,"adresId":1384090,"uitvoeringsdatum":null,"uitvoerder":"aannemer","netbeheerder":null,"dak":null,"buitenmuur":null,"vloer":null,"ramenEnDeuren":null,"elektriciteitEnSanitair":{"netbeheerder":"Eandis"},"hernieuwbareEnergieproductie":null,"gascondensatieketel":null}]}
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example: {"type":"https://datatracker.ietf.org/doc/html/rfc2616#section-10.5.1","title":"Onverwachte fout","status":500,"detail":"Er is een onverwachte fout opgetreden. Raadpleeg de logs voor meer informatie. CorrelatieId = 95d6ba3e-052b-4d10-8e93-63a237542504"}
components:
  schemas:
    Gebouweenheden.Bouwjaren:
      type: object
      properties:
        alle:
          type: integer
          format: int32
          nullable: true
        tot2006:
          type: integer
          format: int32
          nullable: true
        na2006:
          type: integer
          format: int32
          nullable: true
      additionalProperties: false
    Gebouweenheden.EpcLabel:
      type: object
      properties:
        locatie:
          type: string
          nullable: true
        typeLocatie:
          type: string
          nullable: true
        typeGebouw:
          type: string
          nullable: true
        referentiejaar:
          type: integer
          format: int32
          nullable: true
        totaalAangiftesGeoLocatie:
          type: integer
          format: int32
          nullable: true
        totaalEpcGeoLocatie:
          type: integer
          format: int32
          nullable: true
        geldig:
          type: boolean
          nullable: true
        bouwjaren:
          $ref: '#/components/schemas/Gebouweenheden.Bouwjaren'
        labels:
          type: object
          additionalProperties:
            type: number
            format: double
            nullable: true
          nullable: true
      additionalProperties: false
    Gebouweenheden.EpcLabelsLijst:
      type: object
      properties:
        labels:
          type: array
          items:
            $ref: '#/components/schemas/Gebouweenheden.EpcLabel'
          nullable: true
      additionalProperties: false
    Mcs.Eindbeoordeling:
      type: object
      properties:
        isRookgasafvoerkanaalConform:
          type: boolean
          nullable: true
        isStookplaatsConform:
          type: boolean
          nullable: true
        isStooktoestelConform:
          type: boolean
          nullable: true
        isToestelWerkingGoed:
          type: boolean
        isToestelWerkingVeilig:
          type: boolean
        isVerbrandingscontroleConform:
          type: boolean
          nullable: true
      additionalProperties: false
    Mcs.Gegevensactiviteit:
      type: object
      properties:
        type:
          type: string
          nullable: true
        uitvoeringsDatum:
          type: string
          format: date
        wettelijkVerplicht:
          type: boolean
        adresId:
          type: string
          nullable: true
        gebouweenheidId:
          type: string
          nullable: true
        erkenningsnummer:
          type: string
          nullable: true
      additionalProperties: false
    Mcs.KenmerkenToestel:
      type: object
      properties:
        fabricatienummer:
          type: string
          nullable: true
        brandstof:
          type: string
          nullable: true
        merk:
          type: string
          nullable: true
        type:
          type: string
          nullable: true
        bouwjaar:
          type: integer
          format: int32
          nullable: true
        vermogen:
          type: number
          format: double
          nullable: true
      additionalProperties: false
    Mcs.Melding:
      type: object
      properties:
        meldingId:
          type: string
          format: uuid
        geldigTot:
          type: string
          format: date
          nullable: true
        eindbeoordeling:
          $ref: '#/components/schemas/Mcs.Eindbeoordeling'
        activiteit:
          $ref: '#/components/schemas/Mcs.Gegevensactiviteit'
        toestel:
          $ref: '#/components/schemas/Mcs.KenmerkenToestel'
        toestelEindbeoordeling:
          enum:
            - Goedgekeurd
            - Afgekeurd
          type: string
      additionalProperties: false
    Mcs.MeldingenLijst:
      type: object
      properties:
        meldingen:
          type: array
          items:
            $ref: '#/components/schemas/Mcs.Melding'
          nullable: true
      additionalProperties: false
    Mvp.Buitenmuur:
      type: object
      properties:
        type:
          type: string
          nullable: true
        teVerwijderenAsbest:
          type: boolean
          nullable: true
        oppervlakteAsbest:
          type: number
          format: double
          nullable: true
        oppervlakte:
          type: number
          format: double
          nullable: true
        dikteSpouw:
          type: number
          format: double
          nullable: true
        lambdaWaarde:
          type: number
          format: double
          nullable: true
        rdWaarde:
          type: number
          format: double
          nullable: true
        stsNummer:
          type: string
          nullable: true
      additionalProperties: false
    Mvp.Dak:
      type: object
      properties:
        type:
          type: string
          nullable: true
        teVerwijderenAsbest:
          type: boolean
          nullable: true
        oppervlakteAsbest:
          type: number
          format: double
          nullable: true
        oppervlakte:
          type: number
          format: double
          nullable: true
        rdWaarde:
          type: number
          format: double
          nullable: true
      additionalProperties: false
    Mvp.ElektriciteitEnSanitair:
      type: object
      properties:
        netbeheerder:
          type: string
          nullable: true
      additionalProperties: false
    Mvp.Gascondensatieketel:
      type: object
      properties:
        type:
          type: string
          nullable: true
        teVervangenInstallatie:
          $ref: '#/components/schemas/Mvp.TeVervangenInstallatie'
        vervangingHoogrendementsketel:
          type: boolean
          nullable: true
        aardgasnetAanwezig:
          type: boolean
          nullable: true
        productLabel:
          type: string
          nullable: true
        vermogens:
          type: array
          items:
            $ref: '#/components/schemas/Mvp.Vermogen'
          nullable: true
        typeHoofdverwarming:
          type: string
          nullable: true
      additionalProperties: false
    Mvp.HernieuwbareEnergieproductie:
      type: object
      properties:
        type:
          type: string
          nullable: true
        oppervlakte:
          type: number
          format: double
          nullable: true
        productLabel:
          type: string
          nullable: true
        vermogens:
          type: array
          items:
            $ref: '#/components/schemas/Mvp.Vermogen'
          nullable: true
        typeHoofdverwarming:
          type: string
          nullable: true
        energieEfficientie:
          type: string
          nullable: true
        typeAandrijving:
          type: string
          nullable: true
        vervangingElektrischeVerwarming:
          type: boolean
          nullable: true
        aardgasnetAanwezig:
          type: boolean
          nullable: true
        gebruik:
          type: string
          nullable: true
        inhoud:
          type: string
          nullable: true
      additionalProperties: false
    Mvp.RamenEnDeuren:
      type: object
      properties:
        type:
          type: string
          nullable: true
        soortBeglazingTerVervanging:
          type: string
          nullable: true
        uWaarde:
          type: number
          format: double
          nullable: true
        oppervlakte:
          type: number
          format: double
          nullable: true
      additionalProperties: false
    Mvp.TeVervangenInstallatie:
      type: object
      properties:
        type:
          type: string
          nullable: true
        leeftijd:
          type: integer
          format: int32
          nullable: true
      additionalProperties: false
    Mvp.Vermogen:
      type: object
      properties:
        type:
          type: string
          nullable: true
        waarde:
          type: number
          format: double
          nullable: true
      additionalProperties: false
    Mvp.Vloer:
      type: object
      properties:
        type:
          type: string
          nullable: true
        teVerwijderenAsbest:
          type: boolean
          nullable: true
        oppervlakteAsbest:
          type: number
          format: double
          nullable: true
        oppervlakte:
          type: number
          format: double
          nullable: true
        rdWaarde:
          type: number
          format: double
          nullable: true
      additionalProperties: false
    Mvp.Werk:
      type: object
      properties:
        werkId:
          type: string
          nullable: true
        type:
          type: string
          nullable: true
        dossierNummer:
          type: string
          nullable: true
        facturatieDatum:
          type: string
          format: date
          nullable: true
        gebouweenheidId:
          type: integer
          format: int64
        adresId:
          type: integer
          format: int64
          nullable: true
        uitvoeringsdatum:
          type: string
          format: date
          nullable: true
        uitvoerder:
          type: string
          nullable: true
        netbeheerder:
          type: string
          nullable: true
        dak:
          $ref: '#/components/schemas/Mvp.Dak'
        buitenmuur:
          $ref: '#/components/schemas/Mvp.Buitenmuur'
        vloer:
          $ref: '#/components/schemas/Mvp.Vloer'
        ramenEnDeuren:
          $ref: '#/components/schemas/Mvp.RamenEnDeuren'
        elektriciteitEnSanitair:
          $ref: '#/components/schemas/Mvp.ElektriciteitEnSanitair'
        hernieuwbareEnergieproductie:
          $ref: '#/components/schemas/Mvp.HernieuwbareEnergieproductie'
        gascondensatieketel:
          $ref: '#/components/schemas/Mvp.Gascondensatieketel'
      additionalProperties: false
    Mvp.WerkenLijst:
      type: object
      properties:
        werken:
          type: array
          items:
            $ref: '#/components/schemas/Mvp.Werk'
          nullable: true
      additionalProperties: false
    ProblemDetails:
      type: object
      properties:
        type:
          type: string
          nullable: true
        title:
          type: string
          nullable: true
        status:
          type: integer
          format: int32
        detail:
          type: string
          nullable: true
      additionalProperties: false
tags:
  - name: Gebouweenheden
    description: Service voor informatie over gebouweenheden
  - name: Mcs
    description: Service voor informatie over stooktoestellen
  - name: Mvp
    description: Service voor informatie over mijn verbouw premie