openapi: 3.0.4
info:
  title: Veka.DataDienstenContainer.Api
  description: Health services voor DataDiensten
  version: v1
paths:
  /api/datadienstencontainer/v1/health:
    get:
      tags:
        - Health
      summary: Geeft de health check terug voor de module
      description: Geeft een indicatie over de health van de module
      parameters:
        - name: internalDependenciesOnly
          in: query
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: De module heeft een Healthy of Degraded status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthChecks.VekaHealthReport'
        '503':
          description: De module heeft een Unhealthy status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthChecks.VekaHealthReport'
components:
  schemas:
    HealthChecks.VekaHealthReport:
      type: object
      properties:
        status:
          enum:
            - Unhealthy
            - Degraded
            - Healthy
          type: string
        totalDuration:
          type: string
          format: date-span
        components:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/HealthChecks.VekaHealthReportEntry'
          nullable: true
        data:
          type: object
          additionalProperties:
            type: string
          nullable: true
      additionalProperties: false
    HealthChecks.VekaHealthReportEntry:
      type: object
      properties:
        status:
          enum:
            - Unhealthy
            - Degraded
            - Healthy
          type: string
        description:
          type: string
          nullable: true
        duration:
          type: string
          format: date-span
          nullable: true
        exception:
          type: string
          nullable: true
        data:
          type: object
          additionalProperties: { }
          nullable: true
        tags:
          type: array
          items:
            type: string
          nullable: true
      additionalProperties: false