openapi: 3.1.0
info:
  title: VEKA Melding Centrale Stooktoestellen API
  description: Rest API services energie van het Vlaams Energie- en Klimaatagentschap
  contact:
    name: VEKA
    url: https://www.energiesparen.be
    email: veka@vlaanderen.be
  license:
    name: European Union Public Licence (EUPL)
    url: https://joinup.ec.europa.eu/collection/eupl/eupl-text-11-12
  version: "v1"
servers:
  - url: https://energie-dev.api.vlaanderen.be
tags:
  - name: Melding centrale stooktoestellen opladen
    description: Melding Centrale Stooktoestellen voor externe afnemers
paths:
  /attesten-api/v1/extern/meldingCentraleStooktoestellen:
    post:
      tags:
        - Melding centrale stooktoestellen opladen
      summary: Een nieuwe melding voor een centraal stooktoestel opladen.
      operationId: postMelding
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MeldingCentraleStooktoestellenInputRestDtoGegevensActiviteitInputKenmerkenToestelInput"
        required: true
      responses:
        "201":
          description: Het object is aangemaakt.
        "400":
          description: Ongeldige request
          content:
            application/json:
              schema:
                example:
                  detail: Er zijn één of meerdere validatie fouten opgetreden. Controleer
                    het errors attribuut voor meer informatie.
                  status: 400
                  type: https://datatracker.ietf.org/doc/html/rfc2616#section-10.4.1
                  path: /voorbeeld-api/voorbeeld-endpoint
                  title: Bad Request
                  timestamp: 2024-09-02T15:03:37.449+02:00
                  errors:
                    - detail: Minimaal param1 of param2 zijn verplicht.
        "403":
          description: Forbidden
        "500":
          description: Er is een fout opgetreden.
          content:
            application/json:
              schema:
                example:
                  detail: "Onverwachte systeemfout. Error id: 12738bac-8707-4eb2-b746-a7b97e5723a4"
                  status: 500
                  type: https://datatracker.ietf.org/doc/html/rfc2616#section-10.5.1
                  path: /voorbeeld-api/voorbeeld-endpoint/4d3930c8-8c75-433f-a9f1-7684e7cc5000
                  title: Internal Server Error
                  timestamp: 2024-09-03T15:03:37.449+02:00
                  errors:
                    - errorCode: 12738bac-8707-4eb2-b746-a7b97e5723a4
                      detail: "Onverwachte systeemfout. Error id: 12738bac-8707-4eb2-b746-a7b97e5723a4"
  /attesten-api/v1/extern/historischeMeldingCentraleStooktoestellen:
    post:
      tags:
        - Melding centrale stooktoestellen opladen
      summary: Historische melding voor een centraal stooktoestel opladen.
      operationId: postMeldingenInBulk
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MeldingCentraleStooktoestellenInputRestDtoGegevensActiviteitMetAdresInputKenmerkenToestelInput"
        required: true
      responses:
        "201":
          description: Het object is aangemaakt.
        "400":
          description: Ongeldige request
          content:
            application/json:
              schema:
                example:
                  detail: Er zijn één of meerdere validatie fouten opgetreden. Controleer
                    het errors attribuut voor meer informatie.
                  status: 400
                  type: https://datatracker.ietf.org/doc/html/rfc2616#section-10.4.1
                  path: /voorbeeld-api/voorbeeld-endpoint
                  title: Bad Request
                  timestamp: 2024-09-02T15:03:37.449+02:00
                  errors:
                    - detail: Minimaal param1 of param2 zijn verplicht.
        "403":
          description: Forbidden
        "500":
          description: Er is een fout opgetreden.
          content:
            application/json:
              schema:
                example:
                  detail: "Onverwachte systeemfout. Error id: 12738bac-8707-4eb2-b746-a7b97e5723a4"
                  status: 500
                  type: https://datatracker.ietf.org/doc/html/rfc2616#section-10.5.1
                  path: /voorbeeld-api/voorbeeld-endpoint/4d3930c8-8c75-433f-a9f1-7684e7cc5000
                  title: Internal Server Error
                  timestamp: 2024-09-03T15:03:37.449+02:00
                  errors:
                    - errorCode: 12738bac-8707-4eb2-b746-a7b97e5723a4
                      detail: "Onverwachte systeemfout. Error id: 12738bac-8707-4eb2-b746-a7b97e5723a4"
components:
  schemas:
    EindbeoordelingInput:
      type: object
      properties:
        stooktoestelConform:
          type: string
        rookgasafvoerkanaalConform:
          type: string
        stookplaatsConform:
          type: string
        verbrandingscontrole:
          type: string
        toestelWerkingGoed:
          type: string
        toestelWerkingVeilig:
          type: string
      required:
        - toestelWerkingGoed
        - toestelWerkingVeilig
    GegevensActiviteitInput:
      type: object
      description: Gegevens van de activiteit
      properties:
        activiteitType:
          type: string
        erkenningsnummer:
          type: string
          description: Erkenningsnummer van de technicus dat de activiteit heeft uitgevoerd.
          maxLength: 128
          minLength: 0
        verwarmingType:
          type: string
        gebouwId:
          type: string
        gebouwIdNietGekend:
          type: boolean
        gebouweenheidId:
          type: string
        gebouweenheidIdNietGekend:
          type: boolean
        adresId:
          type: string
        datumActiviteit:
          type: string
          format: date
      required:
        - activiteitType
        - adresId
        - datumActiviteit
        - gebouwIdNietGekend
        - gebouweenheidIdNietGekend
        - verwarmingType
    KenmerkenToestelInput:
      type: object
      properties:
        fabricatienummer:
          type: string
          maxLength: 128
          minLength: 0
        fabricatienummerNietGekend:
          type: boolean
        brandstof:
          type: string
        branderTechnologie:
          type: string
        merk:
          type: string
          maxLength: 128
          minLength: 0
        merkNietGekend:
          type: boolean
        type:
          type: string
          maxLength: 128
          minLength: 0
        typeNietGekend:
          type: boolean
        werking:
          type: string
        nominaalVermogen:
          type: number
          format: double
          maximum: 999999.0
          minimum: 0.00
        bouwjaar:
          type: integer
          format: int32
          maximum: 2099
          minimum: 1900
        bouwjaarNietGekend:
          type: boolean
      required:
        - bouwjaarNietGekend
        - brandstof
        - fabricatienummerNietGekend
        - merkNietGekend
        - nominaalVermogen
        - typeNietGekend
        - werking
    MeldingCentraleStooktoestellenInputRestDtoGegevensActiviteitInputKenmerkenToestelInput:
      type: object
      description: MeldingCentraleStooktoestellenInput
      properties:
        externeReferte:
          type: string
          maxLength: 128
          minLength: 0
        ondernemingsnummer:
          type: string
          maxLength: 20
          minLength: 0
        gegevensActiviteit:
          $ref: "#/components/schemas/GegevensActiviteitInput"
        kenmerkenToestel:
          $ref: "#/components/schemas/KenmerkenToestelInput"
        eindbeoordeling:
          $ref: "#/components/schemas/EindbeoordelingInput"
      required:
        - eindbeoordeling
        - gegevensActiviteit
        - kenmerkenToestel
        - ondernemingsnummer
    GegevensActiviteitMetAdresInput:
      type: object
      description: Gegevens van de activiteit voor historische data.
      properties:
        activiteitType:
          type: string
        erkenningsnummer:
          type: string
          description: Erkenningsnummer van de technicus dat de activiteit heeft uitgevoerd.
          maxLength: 128
          minLength: 0
        verwarmingType:
          type: string
        gebouwId:
          type: string
        gebouwIdNietGekend:
          type: boolean
        gebouweenheidId:
          type: string
        gebouweenheidIdNietGekend:
          type: boolean
        datumActiviteit:
          type: string
          format: date
        adresId:
          type: string
        straatnaam:
          type: string
          maxLength: 256
          minLength: 0
        huisnummer:
          type: string
          maxLength: 256
          minLength: 0
        busnummer:
          type: string
          maxLength: 256
          minLength: 0
        postcode:
          type: string
          maxLength: 4
          minLength: 4
        gemeente:
          type: string
          maxLength: 256
          minLength: 0
      required:
        - activiteitType
        - datumActiviteit
        - gebouwIdNietGekend
        - gebouweenheidIdNietGekend
        - verwarmingType
    MeldingCentraleStooktoestellenInputRestDtoGegevensActiviteitMetAdresInputKenmerkenToestelInput:
      type: object
      description: MeldingCentraleStooktoestellenInput
      properties:
        externeReferte:
          type: string
          maxLength: 128
          minLength: 0
        ondernemingsnummer:
          type: string
          maxLength: 20
          minLength: 0
        gegevensActiviteit:
          $ref: "#/components/schemas/GegevensActiviteitMetAdresInput"
        kenmerkenToestel:
          $ref: "#/components/schemas/KenmerkenToestelInput"
        eindbeoordeling:
          $ref: "#/components/schemas/EindbeoordelingInput"
      required:
        - eindbeoordeling
        - gegevensActiviteit
        - kenmerkenToestel
        - ondernemingsnummer
